org: istio
repo: api
support_release_branching: true

defaults:
  branches: [master]
  repo-allowlist: [api]


transforms:

# istio/api master build job(s) - presubmit(s)
- labels:
  job-type: [presubmit]
  job-allowlist: [build, gencheck]

# istio/api master test jobs(s) - postsubmit(s)
- labels:
    preset-override-envoy-r2: "true"
  job-type: [postsubmit]
  job-allowlist: [build, gencheck]
  requirements: [cf-r2-istio-build-private-auth]
